### ISSUE TITLE
[bug] didComponentMount being called each time history is changed

### ISSUE THREAD

**Issue by dasnixon** [pbeshai/react-url-query#10]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A dispatched action in redux, that calls `urlPushInAction`, which changes a single query parameter, causes `componentDidMount` to be called.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

These are the actions being dispatched. You can see the initial load, which stops at `SUCCESS/GROUPED_STATS_DATA`. Then I change a filter, `@@router/LOCATION_CHANGE` occurs, and `didComponentMount` is fired again.

![screen shot 2017-03-28 at 5 44 50 pm](https://cloud.githubusercontent.com/assets/672057/24433548/5a617e22-13de-11e7-84d5-ddda670e5c4d.png)

Console log of `didComponentMount` fired twice

![screen shot 2017-03-28 at 5 45 02 pm](https://cloud.githubusercontent.com/assets/672057/24433551/5c7fe27a-13de-11e7-843b-feb4182cf085.png)

URL `group_by` parameter

![screen shot 2017-03-28 at 5 45 08 pm](https://cloud.githubusercontent.com/assets/672057/24433553/5e3980da-13de-11e7-8eca-a855589a131f.png)

**What is the expected behavior?**
I do not expect a re-mount (`componentDidMount` should only be called once on initial render) if only a query parameter was changed.

**Which versions of react-url-query, and which browser and OS are affected by this issue? Did this work in previous versions of react-url-query?**

On version 1.1.1 of react-url-query

I have a feeling this may have something to do with the higher order component? I don't think this is an issue with `react-router-redux` as I removed it, and still same issues.

**Comment by dasnixon** [comment]
So...I nuked my `node_modules` and re-installed everything. It's working as expected. So weird, sorry to bother you but was banging my head against this. Love the library, thanks!

**Comment by pbeshai** [comment]
Interesting problem. Glad to hear you fixed it!
