### ISSUE TITLE
Concatinating path name

### ISSUE THREAD

**Issue by maettyhawk** [pbeshai/react-url-query#11]
Actually I'm not really sure whether this is a bug or just happening because of me lacking in advanced React skills...

My app base is /path. By using the function *multiPushInUrlQuery* the pathname gets continually concatinated to my url, e.g. if my URL was http://localhost/path the url transforms to http://localhost/path/path after using the mentioned function. I finally ended up setting the pathname property of the newLocation object to '/' manually within the *multiUpdateInLocation* function (updateUrlQuery.js). I've also set the basename to /path when creating my history object and there's a base tag set to /path in my HTML file.

I'm using the current version of react-url-query.

**Comment by pbeshai** [comment]
oooh thanks for finding this! I'm currently away on vacation but when I get a minute I'll see if I can patch it.

**Comment by pbeshai** [comment]
Hi @maettyhawk, do you have a code repo I can see to reproduce this or can you put together a minimal example that exhibits the problem?

**Comment by maettyhawk** [comment]
Hi @pbeshai, sorry, there's no code repo I could share with you besides a modified copy of the module published on npm (react-url-query-fixed-basename). which I'll obviously delete after the problem is solved. I started my project using create-react-app, but in order to configure the basename we ejected it to unveil the hidden webpack configurations. Maybe we did something wrong, but we somehow managed to get to run the app both on the root (http://hostname/) and also using a basename (http://hostname/basename). We're using react-url-query for a filter mechanism, any single filter is represented by a query param (f.e. age=13_40 or name=Scott). The already mentioned bug appears every time I try to use the _multiPushInUrlQuery_ function in the environment using a basename. The basename gets concatinated to the uri everytime the function gets triggered. What I did to solve the problem in my case was to replace the basename in the _pathname_ property of _newLocation_ with '/'. Actually I'm replacing just the first instance by using the replace function.
I could try to reproduce the error within a test project if you need more details.

**Comment by maettyhawk** [comment]
Honestly, I don't think this is a bug. I double-checked within a blank project and it seems to work.

**Comment by pbeshai** [comment]
Ok, thanks for following up!
