### ISSUE TITLE
Empty location.search doesn't taken into account

### ISSUE THREAD

**Issue by syadykin** [pbeshai/react-url-query#12]
I feel [this](https://github.com/pbeshai/react-url-query/blob/master/src/react/addUrlProps.js#L48) must be something like
`if (props.location && (props.location.query || props.location.search !== void(0))) {`

**Comment by pbeshai** [comment]
Fair point! Did this cause a bug for you?

**Comment by syadykin** [comment]
Yes, it did not work for me in isomorphic app. I also had another fix which I closed by mistake earlier but I see it is already have been provided by another guy recently.

**Comment by pbeshai** [comment]
Fixed in 1.1.3
