### ISSUE TITLE
Question - Server Side Rendering

### ISSUE THREAD

**Issue by yoadsn** [pbeshai/react-url-query#25]
Quick verification reg. server side rendering.
Looking at the implementation of the `urlQueryConfig` it's clear the Singleton holds a single reference to the history object.

Due to that, any aysnc rendering on the server could mix up queries from different requests causing chaos.

This library is not designed to work with server side rendering. Right?

Does that imply I should avoid it for some reason? Caring about the query on the first server side render? I can see many use cases for that.

**Comment by pbeshai** [comment]
Good question. I haven't tested it. I think this library should still work in a "read-only" mode without history if you're using react-router (i.e. `location` ends up in `this.props`). I believe if the location is not found in the history, it will next try to read from the props of the component, which should be fine in this case. 

When I have some time I will work on a server-side rendering example.

**Comment by yoadsn** [comment]
@pbeshai Thanks.
For future reference relevant code around the mentioned scenario [here](https://github.com/pbeshai/react-url-query/blob/8ea5afc8691533bea2ee603213222ec22e4d7def/src/react/addUrlProps.js#L49-L60)
