### ISSUE TITLE
defaultValue used as entrySeparator

### ISSUE THREAD

**Issue by JRGranell** [pbeshai/react-url-query#28]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Passing a `default value` for type array uses that value as the entry separator. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
Call `decode` with `decode('array', str_array', []);

**What is the expected behavior?**
['str', 'array'] 

**Actual**
['s', 't', 'r', '_', 'a', 'r', 'r', 'a', y']

**Which versions of react-url-query, and which browser and OS are affected by this issue? Did this work in previous versions of react-url-query?**
v1.2.0
Chrome
Not used before

Looks like https://github.com/pbeshai/react-url-query/blob/master/src/serialize.js#L292 is passing `defaultValue` into func https://github.com/pbeshai/react-url-query/blob/master/src/serialize.js#L140

I would expect the `defaultValue` to be returned from `decode` if the `decodedValue === undefined`. If you pass in `[]` it's using that as the `entrySeparator`

**Comment by pbeshai** [comment]
Good catch, I'll fix today.
