### ISSUE TITLE
Support global `entrySeparator` and `keyValSeparator` configuration in serialisation

### ISSUE THREAD

**Issue by JRGranell** [pbeshai/react-url-query#29]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`entrySeparator` and `keyValSeparator` can be specified when calling individual serialisation functions such as `encodeObject`. `_` is often used in JSON as a way to denote a space, as such it easily breaks many functions that use these default separators.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**
The default is `_` and `-` it would be great to be able to specify these as global config options (perhaps when calling `configureUrlQuery`) rather than having to implement a sugar function that internally calls the native functions - just with a different separator.

**Which versions of react-url-query, and which browser and OS are affected by this issue? Did this work in previous versions of react-url-query?**
N/A

**Comment by JRGranell** [comment]
https://github.com/pbeshai/react-url-query/pull/30

**Comment by pbeshai** [comment]
Will be added in v1.3.0, thanks!

**Comment by pbeshai** [comment]
v1.3.0 now published
