### ISSUE TITLE
Date time support missing

### ISSUE THREAD

**Issue by JRGranell** [pbeshai/react-url-query#39]
**Do you want to request a *feature* or report a *bug*?**
Bug / feature

**What is the current behavior?**
Date encode / decode supports date only. Javascript Date includes time, encoding / decoding should support is as well. Suggest using ISO spec i.e. Date().toISOString();

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**
Support time in date

**Which versions of react-url-query, and which browser and OS are affected by this issue? Did this work in previous versions of react-url-query?**
v1.30

**Comment by pbeshai** [comment]
Good point, I'll add this to https://github.com/pbeshai/serialize-query-params and deal with it there, which this library will soon be updated to use.
