### ISSUE TITLE
Batch URL query updates

### ISSUE THREAD

**Issue by pbeshai** [pbeshai/react-url-query#5]
Would be nice to provide a mechanism to update multiple query parameters at the same time via "batching" multiple replaceIns

**Comment by cowboy** [comment]
One thought I had was to do this kind of thing:

```js
const urlPropsQueryConfig = {
  foo: { type: UrlQueryParamTypes.number },
  bar: { type: UrlQueryParamTypes.number },
};

// This could also be a string prop name like 'onChangeQueryParam'
const onChangeQueryParam = true;

const MyComponent = ({ foo, bar, onChangeFoo, onChangeBar, onChangeQueryParam }) => (
  <div>
    <button onClick={() => onChangeFoo(1)}>Change foo</button>
    <button onClick={() => onChangeBar(2)}>Change bar</button>
    <button onClick={() => onChangeQueryParam({ foo: 3, bar: 4 })}>Change both</button>
  </div>
);

export default addUrlProps({ urlPropsQueryConfig, onChangeQueryParam })(MyComponent);
```

**Comment by pbeshai** [comment]
Yea that could work well. I was considering something like that or maybe doing something similar to [redux-batched-actions](https://github.com/tshelburne/redux-batched-actions), but I hadn't reallly thought it through. Your approach is simple and will probably work nicely, I'll investigate soon.
