### ISSUE TITLE
No new history entry on onChangeX using react-router-v4-and-redux

### ISSUE THREAD

**Issue by mb21** [pbeshai/react-url-query#52]
Currently, using the `/examples/react-router-v4-and-redux` project and clicking one of the `url query param` buttons, no `history.push` is executed.

Is this expected behavoiur? If so, is there a way I can configure `<RouterToUrlQuery>` to make a new history entry if `onChangeBaz` etc. is called?

**Comment by pbeshai** [comment]
I believe the options are to specify `updateType` in the query config e.g.:

```js
arr: { type: UrlQueryParamTypes.array, updateType: UrlUpdateTypes.pushIn },
```

or to use mapChangeHandlersToProps to create the handler kind of like https://peterbeshai.com/react-url-query/docs/api/addUrlProps.html#alternative-usage-with-mapurltoprops

onChangeBaz in this case is not stored in the URL, it's just stored in redux.

**Comment by mb21** [comment]
Thanks for the quick reply, exactly what I was looking for!
