### ISSUE TITLE
remove url query

### ISSUE THREAD

**Issue by ddtch** [pbeshai/react-url-query#55]
Is there API to remove certain url query param or clear all query params?

**Comment by pbeshai** [comment]
If you just want to remove a certain param, your best bet is to set it to `undefined` or `null`.

If you want to modify the set of URL parameters, you can use the update type "replace" or the function [replaceUrlQuery](https://peterbeshai.com/react-url-query/docs/api/replaceUrlQuery.html) and pass the object with just the query params you care about. (Note the default mode is "replaceIn" -- it maintains all params except the one you are changing). You can use the utilities [subquery](https://peterbeshai.com/react-url-query/docs/api/subquery.html) or [subqueryOmit](https://peterbeshai.com/react-url-query/docs/api/subqueryOmit.html) to help create the new query object.

**Comment by pbeshai** [comment]
You can also just use whatever routing system you're using to clear all params.

**Comment by ddtch** [comment]
thank you. my problem solved
