### ISSUE TITLE
Hook to get url state and onChange functions

### ISSUE THREAD

**Issue by ghost** [pbeshai/react-url-query#70]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**
To get URL states and onChange function we have adUrlProps HOC.

**What is the expected behavior?**
To get URL states and onChange function  we have adUrlProps HOC, but I will prefer a hook as that will be more clean way to get state and onChange functions in functional component

**Which versions of react-url-query, and which browser and OS are affected by this issue? Did this work in previous versions of react-url-query?**
`react-query-url: 1.5.0`

**Comment by ghost** [comment]
or is there any way I can convert adUrlProp HOC into a custom hook.

**Comment by pbeshai** [comment]
Please use [use-query-params](https://github.com/pbeshai/use-query-params)
