### ISSUE TITLE
multiReplaceInUrlQuery and other functions not exported from the library

### ISSUE THREAD

**Issue by zefj** [pbeshai/react-url-query#8]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Unable to do `import { multiReplaceInUrlQuery } from 'react-url-query'`.

Hi, multiReplaceInUrlQuery (and as far as I can see a couple of other functions) doesn't seem to be exported from `src/index.js`. It is possible to import them directly from `react-url-query/src/updateUrlQuery.js`, but not from `react-url-query`. Is this intentional?

**Comment by pbeshai** [comment]
That one is not intentional! Thank you for pointing this out. I'll address it soon.

**Comment by pbeshai** [comment]
Hi @zefj, this has been fixed in npm v1.1.1. Thanks for reporting it!
